shellEmulator: true

trustPolicy: no-downgrade
packages:
  - apps/*
  - packages/*
overrides:
  chokidar: ^5.0.0
  semver: ^7.7.3
  undici: ^7.18.2
  undici-types: ^7.18.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - vue-demi
  - workerd
