import type { ContentfulStatusCode } from 'hono/utils/http-status'

export type QuantErrorCode
  = | 'QUANT_INVALID_INPUT'
    | 'QUANT_CAPABILITY_DISABLED'
    | 'QUANT_PROVIDER_CONFIGURATION'
    | 'QUANT_PROVIDER_UNKNOWN_API'
    | 'QUANT_PROVIDER_TIMEOUT'
    | 'QUANT_PROVIDER_QUOTA'
    | 'QUANT_PROVIDER_UPSTREAM'
    | 'QUANT_PROVIDER_INVALID_RESPONSE'
    | 'QUANT_AI_CONFIGURATION'
    | 'QUANT_AI_SUMMARY_CONFIGURATION'
    | 'QUANT_AI_SUMMARY_TIMEOUT'
    | 'QUANT_AI_SUMMARY_UPSTREAM'
    | 'QUANT_AI_SUMMARY_INVALID_RESPONSE'
    | 'QUANT_AI_COMPARISON_CONFIGURATION'
    | 'QUANT_AI_COMPARISON_TIMEOUT'
    | 'QUANT_AI_COMPARISON_UPSTREAM'
    | 'QUANT_AI_COMPARISON_INVALID_RESPONSE'
    | 'QUANT_AI_QUESTION_CONFIGURATION'
    | 'QUANT_AI_QUESTION_TIMEOUT'
    | 'QUANT_AI_QUESTION_UPSTREAM'
    | 'QUANT_AI_QUESTION_INVALID_RESPONSE'
    | 'QUANT_AI_CHANGE_EXPLANATION_CONFIGURATION'
    | 'QUANT_AI_CHANGE_EXPLANATION_TIMEOUT'
    | 'QUANT_AI_CHANGE_EXPLANATION_UPSTREAM'
    | 'QUANT_AI_CHANGE_EXPLANATION_INVALID_RESPONSE'
    | 'QUANT_AI_CANDIDATE_BRIEFING_INPUT'
    | 'QUANT_AI_CANDIDATE_BRIEFING_CONFIGURATION'
    | 'QUANT_AI_CANDIDATE_BRIEFING_TIMEOUT'
    | 'QUANT_AI_CANDIDATE_BRIEFING_UPSTREAM'
    | 'QUANT_AI_CANDIDATE_BRIEFING_INVALID_RESPONSE'
    | 'QUANT_AI_CANDIDATE_BRIEFING_QUESTION_INPUT'
    | 'QUANT_AI_CANDIDATE_BRIEFING_QUESTION_CONFIGURATION'
    | 'QUANT_AI_CANDIDATE_BRIEFING_QUESTION_TIMEOUT'
    | 'QUANT_AI_CANDIDATE_BRIEFING_QUESTION_UPSTREAM'
    | 'QUANT_AI_CANDIDATE_BRIEFING_QUESTION_INVALID_RESPONSE'
    | 'QUANT_AI_CANDIDATE_SESSION_INPUT'
    | 'QUANT_AI_CANDIDATE_SESSION_STALE'
    | 'QUANT_AI_CANDIDATE_SESSION_INVALID'
    | 'QUANT_DECISION_ASSISTANT_INPUT'
    | 'QUANT_DECISION_ASSISTANT_RESEARCH_REQUIRED'
    | 'QUANT_DECISION_ASSISTANT_CONFIGURATION'
    | 'QUANT_DECISION_ASSISTANT_MARKET_UNAVAILABLE'
    | 'QUANT_DECISION_ASSISTANT_TIMEOUT'
    | 'QUANT_DECISION_ASSISTANT_UPSTREAM'
    | 'QUANT_DECISION_ASSISTANT_INVALID_RESPONSE'
    | 'QUANT_DECISION_ASSISTANT_INVALID_SNAPSHOT'
    | 'QUANT_FACTOR_CONFIGURATION'
    | 'QUANT_WATCHLIST_LIMIT'
    | 'QUANT_INVALID_RESEARCH_STATUS'
    | 'QUANT_NOT_FOUND'
    | 'QUANT_SYNC_IN_PROGRESS'
    | 'QUANT_SYNC_REJECTED'

export class QuantError extends Error {
  readonly status: ContentfulStatusCode
  readonly code: QuantErrorCode
  readonly details?: unknown

  constructor(code: QuantErrorCode, message: string, status: ContentfulStatusCode = 400, details?: unknown) {
    super(message)
    this.name = 'QuantError'
    this.code = code
    this.status = status
    this.details = details
  }
}
