export type QuantContractArea = 'workspace' | 'config' | 'market' | 'research' | 'decision' | 'ai'
export type QuantHttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export type QuantResponseContentType = 'application/json' | 'text/event-stream'

export interface QuantEndpointInput {
  readonly params: string | null
  readonly query: string | null
  readonly body: string | null
}

export interface QuantEndpointSuccess {
  readonly status: 200 | 201
  readonly contentType: QuantResponseContentType
  readonly responseSchema: string
}

export interface QuantEndpointError {
  readonly status: 400 | 401 | 404 | 409 | 422 | 429 | 500 | 502 | 503 | 504
  readonly codes: readonly string[]
}

export interface QuantEndpointContract {
  readonly id: string
  readonly area: QuantContractArea
  readonly method: QuantHttpMethod
  readonly path: string
  readonly operationId: string
  readonly summary: string
  readonly input: QuantEndpointInput
  readonly success: QuantEndpointSuccess
  readonly errors: readonly QuantEndpointError[]
  readonly consumer: string
}

const unauthorized: QuantEndpointError = { status: 401, codes: ['UNAUTHORIZED'] }
const invalidInput: QuantEndpointError = { status: 400, codes: ['QUANT_INVALID_INPUT'] }
const notFound: QuantEndpointError = { status: 404, codes: ['QUANT_NOT_FOUND'] }
const providerFailure: QuantEndpointError = {
  status: 502,
  codes: ['QUANT_PROVIDER_CONFIGURATION', 'QUANT_PROVIDER_UNKNOWN_API', 'QUANT_PROVIDER_TIMEOUT', 'QUANT_PROVIDER_QUOTA', 'QUANT_PROVIDER_UPSTREAM', 'QUANT_PROVIDER_INVALID_RESPONSE'],
}
const aiSummaryFailure: QuantEndpointError = {
  status: 503,
  codes: ['QUANT_AI_SUMMARY_CONFIGURATION', 'QUANT_AI_SUMMARY_TIMEOUT', 'QUANT_AI_SUMMARY_UPSTREAM', 'QUANT_AI_SUMMARY_INVALID_RESPONSE'],
}

export const quantEndpointContracts = [
  {
    id: 'workspace.watchlist.list',
    area: 'workspace',
    method: 'GET',
    path: '/watchlist',
    operationId: 'listQuantWatchlist',
    summary: '获取观察池',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantWatchlistResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.watchlist.create',
    area: 'workspace',
    method: 'POST',
    path: '/watchlist',
    operationId: 'createQuantWatchlist',
    summary: '加入观察池',
    input: { params: null, query: null, body: 'QuantWatchlistCreateSchema' },
    success: { status: 201, contentType: 'application/json', responseSchema: 'QuantWatchlistItemResponseSchema' },
    errors: [unauthorized, invalidInput, { status: 429, codes: ['QUANT_WATCHLIST_LIMIT'] }, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.watchlist.update',
    area: 'workspace',
    method: 'PATCH',
    path: '/watchlist/:tsCode',
    operationId: 'updateQuantWatchlist',
    summary: '更新观察池名称',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: 'QuantWatchlistUpdateSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantWatchlistItemResponseSchema' },
    errors: [unauthorized, invalidInput, notFound],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.watchlist.delete',
    area: 'workspace',
    method: 'DELETE',
    path: '/watchlist/:tsCode',
    operationId: 'deleteQuantWatchlist',
    summary: '移除观察池代码',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantWatchlistDeleteResponseSchema' },
    errors: [unauthorized, invalidInput, notFound],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.stockBasic.get',
    area: 'workspace',
    method: 'GET',
    path: '/stock-basic/:tsCode',
    operationId: 'getQuantStockBasic',
    summary: '获取股票基础信息',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantStockBasicResponseSchema' },
    errors: [unauthorized, invalidInput, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.daily.list',
    area: 'workspace',
    method: 'GET',
    path: '/daily/:tsCode',
    operationId: 'listQuantDailyBars',
    summary: '获取日线数据',
    input: { params: 'QuantWatchlistParamSchema', query: 'QuantDailyQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantDailyBarsResponseSchema' },
    errors: [unauthorized, invalidInput],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.sync.get',
    area: 'workspace',
    method: 'GET',
    path: '/sync',
    operationId: 'getQuantSyncState',
    summary: '获取同步状态',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantSyncStateResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.sync.run',
    area: 'workspace',
    method: 'POST',
    path: '/sync',
    operationId: 'runQuantSync',
    summary: '同步观察池日线',
    input: { params: null, query: null, body: 'QuantSyncSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantSyncResultResponseSchema' },
    errors: [unauthorized, invalidInput, { status: 409, codes: ['QUANT_SYNC_IN_PROGRESS', 'QUANT_SYNC_REJECTED'] }, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/workspace.ts',
  },
  {
    id: 'workspace.candidates.list',
    area: 'workspace',
    method: 'GET',
    path: '/candidates',
    operationId: 'listQuantCandidates',
    summary: '获取当前候选快照',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantCandidateSnapshotResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/candidate.ts',
  },

  {
    id: 'config.capabilities.get',
    area: 'config',
    method: 'GET',
    path: '/capabilities',
    operationId: 'getQuantCapabilities',
    summary: '获取数据能力',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantCapabilitiesResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.knowledge.get',
    area: 'config',
    method: 'GET',
    path: '/knowledge',
    operationId: 'getQuantInvestmentKnowledge',
    summary: '获取投资因子知识',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantInvestmentKnowledgeResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.ai.get',
    area: 'config',
    method: 'GET',
    path: '/ai-config',
    operationId: 'getQuantAiConfig',
    summary: '获取 AI 配置',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiConfigResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.factor.get',
    area: 'config',
    method: 'GET',
    path: '/factor-config',
    operationId: 'getQuantFactorConfiguration',
    summary: '获取因子配置',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantFactorConfigurationResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.factor.update',
    area: 'config',
    method: 'PUT',
    path: '/factor-config',
    operationId: 'updateQuantFactorConfiguration',
    summary: '更新因子配置',
    input: { params: null, query: null, body: 'QuantFactorConfigUpdateSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantFactorConfigurationResponseSchema' },
    errors: [unauthorized, invalidInput, { status: 422, codes: ['QUANT_FACTOR_CONFIGURATION'] }],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.factor.delete',
    area: 'config',
    method: 'DELETE',
    path: '/factor-config',
    operationId: 'resetQuantFactorConfiguration',
    summary: '恢复默认因子配置',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantFactorConfigurationResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.ai.update',
    area: 'config',
    method: 'PUT',
    path: '/ai-config',
    operationId: 'updateQuantAiConfig',
    summary: '更新 AI 配置',
    input: { params: null, query: null, body: 'QuantAiConfigUpdateSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiConfigResponseSchema' },
    errors: [unauthorized, invalidInput, { status: 503, codes: ['QUANT_AI_CONFIGURATION'] }],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.ai.test',
    area: 'config',
    method: 'POST',
    path: '/ai-config/test',
    operationId: 'testQuantAiConfig',
    summary: '测试 AI 连接',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiConnectionTestResponseSchema' },
    errors: [unauthorized, aiSummaryFailure],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },
  {
    id: 'config.ai.delete',
    area: 'config',
    method: 'DELETE',
    path: '/ai-config',
    operationId: 'deleteQuantAiConfig',
    summary: '删除 AI 配置',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiConfigDeleteResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/config.ts',
  },

  {
    id: 'market.valuation.get',
    area: 'market',
    method: 'GET',
    path: '/valuation/:tsCode',
    operationId: 'getQuantValuation',
    summary: '获取估值快照',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantValuationResponseSchema' },
    errors: [unauthorized, invalidInput, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },
  {
    id: 'market.valuation.compare',
    area: 'market',
    method: 'GET',
    path: '/valuation/compare/:tsCode',
    operationId: 'compareQuantValuation',
    summary: '比较观察池估值',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantValuationComparisonResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },
  {
    id: 'market.financial.get',
    area: 'market',
    method: 'GET',
    path: '/financial/:tsCode',
    operationId: 'getQuantFinancialQuality',
    summary: '获取财务质量',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantFinancialQualityResponseSchema' },
    errors: [unauthorized, invalidInput, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },
  {
    id: 'market.financial.history',
    area: 'market',
    method: 'GET',
    path: '/financial/history/:tsCode',
    operationId: 'getQuantFinancialQualityHistory',
    summary: '获取财务历史',
    input: { params: 'QuantWatchlistParamSchema', query: 'QuantFinancialHistoryQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantFinancialQualityHistoryResponseSchema' },
    errors: [unauthorized, invalidInput, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },
  {
    id: 'market.financial.compare',
    area: 'market',
    method: 'GET',
    path: '/financial/compare/:tsCode',
    operationId: 'compareQuantFinancialQuality',
    summary: '比较观察池财务质量',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantFinancialQualityComparisonResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },
  {
    id: 'market.valueSelection.get',
    area: 'market',
    method: 'GET',
    path: '/value-selection',
    operationId: 'getQuantValueSelection',
    summary: '获取价值质量筛选',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantValueSelectionResponseSchema' },
    errors: [unauthorized, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },
  {
    id: 'market.shareholderReturns.get',
    area: 'market',
    method: 'GET',
    path: '/shareholder-returns',
    operationId: 'getQuantShareholderReturns',
    summary: '获取股东回报',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantShareholderReturnsResponseSchema' },
    errors: [unauthorized, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/market.ts',
  },

  {
    id: 'research.markers.list',
    area: 'research',
    method: 'GET',
    path: '/research',
    operationId: 'listQuantResearchMarkers',
    summary: '获取研究标记',
    input: { params: null, query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchMarkersResponseSchema' },
    errors: [unauthorized],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.runs.create',
    area: 'research',
    method: 'POST',
    path: '/research/runs',
    operationId: 'createQuantResearchRun',
    summary: '生成研究报告',
    input: { params: null, query: null, body: 'QuantResearchRunCreateSchema' },
    success: { status: 201, contentType: 'application/json', responseSchema: 'QuantResearchRunResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.summary.generate',
    area: 'research',
    method: 'POST',
    path: '/research/runs/:runId/summary',
    operationId: 'generateQuantResearchSummary',
    summary: '生成研究摘要',
    input: { params: 'QuantResearchRunIdParamSchema', query: null, body: null },
    success: { status: 201, contentType: 'application/json', responseSchema: 'QuantResearchSummaryResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, aiSummaryFailure],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.summary.stream',
    area: 'research',
    method: 'POST',
    path: '/research/runs/:runId/summary/stream',
    operationId: 'streamQuantResearchSummary',
    summary: '流式生成研究摘要',
    input: { params: 'QuantResearchRunIdParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'text/event-stream', responseSchema: 'QuantResearchSummaryStreamEventSchema' },
    errors: [unauthorized, invalidInput, notFound, aiSummaryFailure],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.question.ask',
    area: 'research',
    method: 'POST',
    path: '/research/runs/:runId/question',
    operationId: 'askQuantResearchQuestion',
    summary: '追问研究报告',
    input: { params: 'QuantResearchRunIdParamSchema', query: null, body: 'QuantResearchQuestionSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchQuestionResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 503, codes: ['QUANT_AI_QUESTION_CONFIGURATION', 'QUANT_AI_QUESTION_TIMEOUT', 'QUANT_AI_QUESTION_UPSTREAM', 'QUANT_AI_QUESTION_INVALID_RESPONSE'] }],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.changeExplanation.generate',
    area: 'research',
    method: 'POST',
    path: '/research/runs/:runId/change-explanation',
    operationId: 'generateQuantResearchChangeExplanation',
    summary: '生成研究变化解释',
    input: { params: 'QuantResearchRunIdParamSchema', query: null, body: 'QuantResearchChangeExplanationSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchChangeExplanationResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 503, codes: ['QUANT_AI_CHANGE_EXPLANATION_CONFIGURATION', 'QUANT_AI_CHANGE_EXPLANATION_TIMEOUT', 'QUANT_AI_CHANGE_EXPLANATION_UPSTREAM', 'QUANT_AI_CHANGE_EXPLANATION_INVALID_RESPONSE'] }],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.comparison.generate',
    area: 'research',
    method: 'POST',
    path: '/research/comparison',
    operationId: 'compareQuantResearchRuns',
    summary: '比较研究报告',
    input: { params: null, query: null, body: 'QuantResearchComparisonSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchComparisonResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 503, codes: ['QUANT_AI_COMPARISON_CONFIGURATION', 'QUANT_AI_COMPARISON_TIMEOUT', 'QUANT_AI_COMPARISON_UPSTREAM', 'QUANT_AI_COMPARISON_INVALID_RESPONSE'] }],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.summary.list',
    area: 'research',
    method: 'GET',
    path: '/research/runs/:runId/summary',
    operationId: 'listQuantResearchSummaries',
    summary: '获取研究摘要历史',
    input: { params: 'QuantResearchRunIdParamSchema', query: 'QuantResearchSummaryQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchSummariesResponseSchema' },
    errors: [unauthorized, invalidInput, notFound],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.aiAudits.list',
    area: 'research',
    method: 'GET',
    path: '/research/runs/:runId/ai-audits',
    operationId: 'listQuantAiRunAudits',
    summary: '获取 AI 运行审计',
    input: { params: 'QuantResearchRunIdParamSchema', query: 'QuantResearchSummaryQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiRunAuditsResponseSchema' },
    errors: [unauthorized, invalidInput, notFound],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.runs.list',
    area: 'research',
    method: 'GET',
    path: '/research/runs/:tsCode',
    operationId: 'listQuantResearchRuns',
    summary: '获取研究运行历史',
    input: { params: 'QuantWatchlistParamSchema', query: 'QuantResearchRunsQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchRunsResponseSchema' },
    errors: [unauthorized, invalidInput],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },
  {
    id: 'research.markers.update',
    area: 'research',
    method: 'PUT',
    path: '/research/:tsCode',
    operationId: 'updateQuantResearchMarker',
    summary: '更新研究标记',
    input: { params: 'QuantWatchlistParamSchema', query: null, body: 'QuantResearchMarkerUpdateSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantResearchMarkerResponseSchema' },
    errors: [unauthorized, invalidInput],
    consumer: 'apps/quant-app/src/api/resources/research.ts',
  },

  {
    id: 'decision.assistant.create',
    area: 'decision',
    method: 'POST',
    path: '/decision-assistant',
    operationId: 'createQuantDecisionAssistant',
    summary: '生成决策助手评估',
    input: { params: null, query: null, body: 'QuantDecisionAssistantCreateSchema' },
    success: { status: 201, contentType: 'application/json', responseSchema: 'QuantDecisionAssistantResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 422, codes: ['QUANT_DECISION_ASSISTANT_RESEARCH_REQUIRED', 'QUANT_DECISION_ASSISTANT_INPUT'] }, { status: 503, codes: ['QUANT_DECISION_ASSISTANT_CONFIGURATION', 'QUANT_DECISION_ASSISTANT_MARKET_UNAVAILABLE'] }, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/decision.ts',
  },
  {
    id: 'decision.assistant.list',
    area: 'decision',
    method: 'GET',
    path: '/decision-assistant/:tsCode',
    operationId: 'listQuantDecisionAssistants',
    summary: '获取决策助手历史',
    input: { params: 'QuantWatchlistParamSchema', query: 'QuantDecisionRecordQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantDecisionAssistantListResponseSchema' },
    errors: [unauthorized, invalidInput, { status: 500, codes: ['QUANT_DECISION_ASSISTANT_INVALID_SNAPSHOT', 'QUANT_PROVIDER_INVALID_RESPONSE'] }],
    consumer: 'apps/quant-app/src/api/resources/decision.ts',
  },
  {
    id: 'decision.record.get',
    area: 'decision',
    method: 'GET',
    path: '/research/runs/:runId/decision',
    operationId: 'getQuantDecisionRecord',
    summary: '获取研究决策记录',
    input: { params: 'QuantResearchRunIdParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantDecisionRecordResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 500, codes: ['QUANT_PROVIDER_INVALID_RESPONSE'] }],
    consumer: 'apps/quant-app/src/api/resources/decision.ts',
  },
  {
    id: 'decision.record.upsert',
    area: 'decision',
    method: 'PUT',
    path: '/research/runs/:runId/decision',
    operationId: 'saveQuantDecisionRecord',
    summary: '保存研究决策记录',
    input: { params: 'QuantResearchRunIdParamSchema', query: null, body: 'QuantDecisionRecordUpdateSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantDecisionRecordResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 500, codes: ['QUANT_PROVIDER_INVALID_RESPONSE'] }],
    consumer: 'apps/quant-app/src/api/resources/decision.ts',
  },
  {
    id: 'decision.queue.list',
    area: 'decision',
    method: 'GET',
    path: '/research/decisions',
    operationId: 'listQuantDecisionQueue',
    summary: '获取决策队列',
    input: { params: null, query: 'QuantDecisionRecordQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantDecisionRecordsResponseSchema' },
    errors: [unauthorized, invalidInput],
    consumer: 'apps/quant-app/src/api/resources/decision.ts',
  },
  {
    id: 'decision.records.list',
    area: 'decision',
    method: 'GET',
    path: '/research/decisions/:tsCode',
    operationId: 'listQuantDecisionRecords',
    summary: '获取标的决策历史',
    input: { params: 'QuantWatchlistParamSchema', query: 'QuantDecisionRecordQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantDecisionRecordsResponseSchema' },
    errors: [unauthorized, invalidInput],
    consumer: 'apps/quant-app/src/api/resources/decision.ts',
  },

  {
    id: 'ai.candidateSessions.list',
    area: 'ai',
    method: 'GET',
    path: '/candidates/ai-sessions',
    operationId: 'listQuantCandidateAiSessions',
    summary: '获取候选 AI 会话',
    input: { params: null, query: 'QuantAiCandidateBriefingSessionQuerySchema', body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiCandidateBriefingSessionListResponseSchema' },
    errors: [unauthorized, invalidInput],
    consumer: 'apps/quant-app/src/api/resources/candidate.ts',
  },
  {
    id: 'ai.candidateSessions.get',
    area: 'ai',
    method: 'GET',
    path: '/candidates/ai-sessions/:sessionId',
    operationId: 'getQuantCandidateAiSession',
    summary: '获取候选 AI 会话详情',
    input: { params: 'QuantAiCandidateBriefingSessionIdParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiCandidateBriefingSessionResponseSchema' },
    errors: [unauthorized, invalidInput, notFound],
    consumer: 'apps/quant-app/src/api/resources/candidate.ts',
  },
  {
    id: 'ai.candidateSessions.delete',
    area: 'ai',
    method: 'DELETE',
    path: '/candidates/ai-sessions/:sessionId',
    operationId: 'deleteQuantCandidateAiSession',
    summary: '删除候选 AI 会话',
    input: { params: 'QuantAiCandidateBriefingSessionIdParamSchema', query: null, body: null },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiCandidateBriefingSessionDeleteResponseSchema' },
    errors: [unauthorized, invalidInput, notFound],
    consumer: 'apps/quant-app/src/api/resources/candidate.ts',
  },
  {
    id: 'ai.candidateBriefing.generate',
    area: 'ai',
    method: 'POST',
    path: '/candidates/ai-briefing',
    operationId: 'generateQuantCandidateAiBriefing',
    summary: '生成候选 AI 简报',
    input: { params: null, query: null, body: 'QuantAiCandidateBriefingRequestSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiCandidateBriefingResponseSchema' },
    errors: [unauthorized, invalidInput, { status: 422, codes: ['QUANT_AI_CANDIDATE_BRIEFING_INPUT'] }, { status: 503, codes: ['QUANT_AI_CANDIDATE_BRIEFING_CONFIGURATION'] }, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/candidate.ts',
  },
  {
    id: 'ai.candidateBriefing.question',
    area: 'ai',
    method: 'POST',
    path: '/candidates/ai-briefing/question',
    operationId: 'askQuantCandidateAiBriefingQuestion',
    summary: '追问候选 AI 简报',
    input: { params: null, query: null, body: 'QuantAiCandidateBriefingQuestionRequestSchema' },
    success: { status: 200, contentType: 'application/json', responseSchema: 'QuantAiCandidateBriefingQuestionResponseSchema' },
    errors: [unauthorized, invalidInput, notFound, { status: 422, codes: ['QUANT_AI_CANDIDATE_BRIEFING_QUESTION_INPUT', 'QUANT_AI_CANDIDATE_SESSION_STALE'] }, { status: 503, codes: ['QUANT_AI_CANDIDATE_BRIEFING_QUESTION_CONFIGURATION'] }, providerFailure],
    consumer: 'apps/quant-app/src/api/resources/candidate.ts',
  },
] as const satisfies readonly QuantEndpointContract[]

export type QuantEndpointId = typeof quantEndpointContracts[number]['id']

export function quantEndpointKey(method: QuantHttpMethod, path: string): string {
  return `${method} ${path}`
}

export function quantEndpointContractKey(contract: QuantEndpointContract): string {
  return quantEndpointKey(contract.method, contract.path)
}
