// @vitest-environment happy-dom

import type { CandidateItem, CandidateSignalPersistence, WatchlistItem } from '../../lib/quant-view-models'
import type { ResearchPriority } from '../../lib/research-priority'
import type { QuantResearchDetailProps } from '../QuantResearchDetailView.vue'
import { shallowMount } from '@vue/test-utils'
import { describe, expect, it, vi } from 'vitest'
import QuantResearchDetailView from '../QuantResearchDetailView.vue'

const stock: WatchlistItem = {
  id: 'watch-1',
  tsCode: '601899.SH',
  name: '测试股票',
  latestTradeDate: '20260903',
  barCount: 120,
  latestClose: 10,
  latestChangePercent: 1.2,
  createdAt: '2026-09-03T00:00:00.000Z',
}

const candidate: CandidateItem = {
  id: 'candidate-1',
  tsCode: stock.tsCode,
  factorVersion: 'momentum-v1',
  name: stock.name,
  score: 3,
  close: 10,
  changePercent: 1.2,
  ma5: 9.8,
  ma20: 9.4,
  return20: 4.5,
  newHigh20: true,
  upStreak: 2,
  volumeRatio: 1.1,
  relativeStrength: 0.8,
  signals: ['ma20'],
  missingFactors: [],
  quality: 'ready',
}

const persistence: CandidateSignalPersistence = {
  sampleSize: 2,
  appearanceCount: 2,
  persistenceRate: 1,
  latestScore: 3,
  previousScore: 2,
  scoreDelta: 1,
  scoreChange: 1,
  state: 'confirming',
  factorPersistence: [],
  evidence: [],
}

const priority: ResearchPriority = {
  level: 'normal',
  levelLabel: '常规研究',
  action: 'continue-research',
  actionLabel: '继续研究',
  tone: 'positive',
  score: 30,
  reasons: ['有信号'],
  breakdown: { dataGap: 0, review: 0, risk: 0, valueQuality: 0, persistence: 2, marker: 0 },
  reviewState: 'unscheduled',
  markerStatus: 'unreviewed',
}

function baseProps(loadResearchRuns: (tsCode: string) => void): QuantResearchDetailProps {
  const emptyTrend = {
    return5: null,
    return20: null,
    return60: null,
    ma20Gap: null,
    drawdown60: null,
    availableBars: 0,
    tone: 'neutral' as const,
    conclusion: '暂无足够日线数据',
  }
  const emptyTiming = {
    state: 'insufficient' as const,
    tone: 'neutral' as const,
    label: '数据不足',
    headline: '数据不足',
    availableBars: 0,
    ma20Gap: null,
    ma60Gap: null,
    pullback20: null,
    volatility20: null,
    metrics: [],
  }
  const emptyHistory = {
    availableBars: 0,
    evaluatedWindows: 0,
    forwardDays: 20,
    dataStartDate: null,
    dataEndDate: null,
    evaluationStartDate: null,
    evaluationEndDate: null,
    currentState: 'insufficient' as const,
    currentLabel: '数据不足',
    observations: [],
    buckets: [],
  }
  const emptyTimeline = {
    points: [],
    totalRunCount: 0,
    latestScore: null,
    previousScore: null,
    latestScoreDelta: null,
    latestScoreDirection: 'none' as const,
    statusChangeCount: 0,
    actionChangeCount: 0,
  }
  const formatNumber = (value: number | null) => value === null ? '--' : value.toFixed(2)
  const formatPercent = (value: number | null) => value === null ? '--' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`
  const noop = () => {}

  return {
    selectedStock: stock,
    selectedCandidate: { ...candidate, persistence },
    selectedResearchMarker: {
      tsCode: stock.tsCode,
      status: 'unreviewed',
      note: null,
      reviewDate: null,
      createdAt: null,
      updatedAt: null,
    },
    selectedResearchReview: { state: 'unscheduled', label: '未设置', detail: '尚未设置复查日期', tone: 'neutral', date: null },
    researchStatusOptions: [
      { value: 'unreviewed', label: '待研究' },
      { value: 'priority', label: '重点关注' },
      { value: 'paused', label: '暂缓' },
      { value: 'excluded', label: '已排除' },
    ],
    signalRuleCount: 6,
    latestResearchRun: null,
    latestResearchReport: null,
    researchRuns: [],
    researchRunLoading: false,
    researchRunGenerating: false,
    researchRunErrorMessage: '研究历史读取失败',
    researchSummary: null,
    researchAiSummary: null,
    researchSummaryLoading: false,
    researchSummaryGenerating: false,
    researchSummaryErrorMessage: null,
    researchSummaryStreamMode: null,
    researchSummaryStreamReceivedChars: 0,
    researchSummaryConfigurationError: false,
    researchAiAudits: [],
    researchAiAuditsLoading: false,
    researchAiAuditErrorMessage: null,
    researchQuestion: null,
    researchQuestionLoading: false,
    researchQuestionErrorMessage: null,
    researchQuestionConfigurationError: false,
    researchQuestionPromptReady: false,
    researchChangeExplanation: null,
    researchChangeExplanationGenerating: false,
    researchChangeExplanationErrorMessage: null,
    researchChangeExplanationConfigurationError: false,
    researchDecisionRecord: null,
    researchDecisionHistory: [],
    researchDecisionLoading: false,
    researchDecisionHistoryLoading: false,
    researchDecisionSaving: false,
    researchDecisionLoadErrorMessage: null,
    researchDecisionHistoryErrorMessage: null,
    researchDecisionSaveErrorMessage: null,
    researchDecisionSaveMessage: '',
    researchSaving: false,
    researchSaveMessage: '',
    researchSaveErrorMessage: null,
    decisionAssistant: null,
    decisionAssistantHistory: [],
    decisionAssistantLoading: false,
    decisionAssistantGenerating: false,
    decisionAssistantErrorMessage: null,
    decisionAssistantAiConfigAvailable: null,
    dailyBars: [],
    dailyColumns: [],
    chartBars: [],
    latestDailyBar: null,
    latestDate: '2026-09-03',
    trendStructure: emptyTrend,
    timingWindow: emptyTiming,
    timingHistory: emptyHistory,
    timingHistoryCurrentBucket: null,
    decisionEvidence: null,
    valuation: null,
    valuationComparison: null,
    hasValuationData: false,
    financialQuality: null,
    financialHistory: null,
    financialComparison: null,
    financialComparisonError: null,
    hasFinancialData: false,
    financialTrendItems: [],
    selectedValueQuality: null,
    selectedShareholderReturn: null,
    loading: { daily: false, valuation: false, financial: false, valueQuality: false, shareholderReturns: false },
    errors: { daily: null, valuation: null, financial: null, valueQuality: null, shareholderReturns: null },
    decisionFreshness: 'fresh',
    decisionFreshnessDetail: '数据新鲜',
    researchEvidenceGroups: [],
    researchEvidenceComparison: null,
    researchRunTimeline: emptyTimeline,
    researchReportCopying: false,
    researchReportCopyOutcome: null,
    researchReportCopyMessage: '',
    selectedTsCode: stock.tsCode,
    formatNumber,
    formatPercent,
    formatSignalScore: value => value === null ? '--' : `${value} / 6`,
    formatFactorLabel: value => value,
    formatDateTime: value => value || '--',
    formatTradeDate: value => value || '--',
    formatEvidenceDate: value => value || '未记录',
    formatComparisonPosition: value => value === null ? '--' : String(value),
    formatLowerComparisonPosition: value => value === null ? '--' : String(value),
    formatMarketCap: formatNumber,
    formatFinancialAmount: formatNumber,
    formatMetricPercent: formatPercent,
    formatRatioPercent: formatPercent,
    formatMultiple: formatNumber,
    formatDividendYield: formatPercent,
    formatTrendDelta: value => value === null ? '--' : String(value),
    formatPersistenceRate: value => value === null ? '--' : String(value),
    formatScoreDelta: value => value === null ? '--' : String(value),
    scoreDeltaClass: value => value === null ? 'text-status-neutral' : 'text-status-success',
    candidatePersistenceFor: () => persistence,
    candidatePersistenceLabel: () => '持续确认',
    candidatePersistenceClass: () => 'candidate-persistence-confirming',
    candidatePriorityFor: () => priority,
    researchPriorityDetail: () => '有信号',
    researchPriorityActionClass: () => 'research-priority-action-positive',
    researchRunStatusLabel: () => '证据完整',
    researchRunStatusClass: () => 'research-run-status-ready',
    researchRunActionLabel: () => '进入研究窗口',
    researchEvidenceStatusLabel: () => '通过',
    researchEvidenceStatusClass: () => 'research-run-evidence-pass',
    formatResearchEvidenceValue: () => '--',
    researchEvidenceChangeClass: () => 'research-evidence-change-changed',
    formatResearchEvidenceDelta: () => '--',
    researchEvidenceHistoryValue: () => '--',
    researchEvidenceHistoryStatus: () => '--',
    researchRunTimelineScoreClass: () => 'research-run-timeline-score-none',
    formatResearchRunTimelineScore: () => '--',
    formatResearchRunTimelineDelta: () => '--',
    formatResearchRunSourceDate: value => value || '未记录',
    timingWindowClass: () => 'timing-window-neutral',
    timingWindowMetricClass: () => 'timing-window-metric-missing',
    timingWindowMetricStatusLabel: () => '数据不足',
    formatTimingWindowMetric: () => '--',
    timingHistoryStateClass: () => 'timing-history-state-insufficient',
    formatTimingHistoryRate: () => '--',
    formatTimingHistoryPercent: () => '--',
    timingHistoryBucketTitle: () => '历史回看',
    decisionEvidenceStatusLabel: () => '通过',
    decisionEvidenceStatusClass: () => 'decision-evidence-status-pass',
    decisionEvidenceActionClass: () => 'decision-evidence-action-research-window',
    shareholderReturnStatusLabel: () => '暂无数据',
    shareholderReturnStatusClass: () => 'value-quality-status-muted',
    shareholderReturnHeaderLabel: () => '分红数据源未配置',
    shareholderReturnSourceLabel: () => '分红数据源未配置',
    valuationErrorMessage: '估值请求失败',
    valuationComparisonErrorMessage: null,
    valueQualityStatusLabel: () => '暂无评分',
    valueQualityStatusClass: () => 'value-quality-status-muted',
    formatValueQualityScore: () => '--',
    formatValueQualityDimension: () => '--',
    valueQualityDimensionSamples: () => 0,
    researchEvidenceDomId: (tsCode, evidenceKey) => `${tsCode}-${evidenceKey}`,
    parsedError: error => ({ type: 'unknown', message: error instanceof Error ? error.message : '请求失败', originalError: error }),
    focusResearchQuestionEvidence: noop,
    generateResearchReport: noop,
    downloadResearchReport: noop,
    copyResearchReport: noop,
    loadResearchRuns,
    generateResearchSummary: noop,
    createDecisionAssistant: noop,
    saveResearchDecision: noop,
    loadDailyBars: noop,
    loadValuation: noop,
    loadFinancialQuality: noop,
    loadValueSelection: noop,
    loadShareholderReturns: noop,
    saveResearchMarker: noop,
    askResearchQuestion: noop,
    generateResearchChangeExplanation: noop,
    useResearchSummaryNextCheck: noop,
    useResearchChangeNextCheck: noop,
  }
}

describe('quant research detail view', () => {
  it('keeps research history retry and marker models at the view boundary', async () => {
    const loadResearchRuns = vi.fn((tsCode: string) => {
      void tsCode
    })
    const wrapper = shallowMount(QuantResearchDetailView, {
      props: {
        ...baseProps(loadResearchRuns),
        researchFormStatus: 'unreviewed',
        researchFormNote: '',
        researchFormReviewDate: '',
        researchQuestionInput: '',
      },
      global: {
        stubs: {
          QuantResearchRunSection: false,
          QuantResearchMarkerEditor: false,
        },
      },
    })

    expect(wrapper.text()).toContain('研究历史读取失败')
    await wrapper.get('.research-run-state-error .text-button').trigger('click')
    expect(loadResearchRuns).toHaveBeenCalledWith(stock.tsCode)

    await wrapper.get('.research-marker-form select').setValue('priority')
    expect(wrapper.emitted('update:researchFormStatus')).toEqual([['priority']])
    await wrapper.get('.research-marker-form textarea').setValue('核对报告期')
    expect(wrapper.emitted('update:researchFormNote')).toEqual([['核对报告期']])
  })
})
