import type { Database } from '@starye/db'
import type { Auth, Env } from './lib/auth'
import { zValidator } from '@hono/zod-validator'
import { createDb } from '@starye/db'
import { media } from '@starye/db/schema'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { HTTPException } from 'hono/http-exception'
import { z } from 'zod'

import { getAllowedOrigins } from './config'
import { createAuth } from './lib/auth'
import { generatePresignedUrl } from './lib/r2'
import { serviceAuth } from './middleware/service-auth'

interface Variables {
  db: Database
  auth: Auth
}

const app = new Hono<{ Bindings: Env, Variables: Variables }>()

// Middleware
app.use(
  '*',
  cors({
    origin: (origin, c) => {
      const allowed = getAllowedOrigins(c.env)
      return allowed.includes(origin) ? origin : allowed[0]
    },
    credentials: true,
    allowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowHeaders: ['Content-Type', 'Authorization'],
  }),
)

// Database & Auth Injection
app.use(async (c, next) => {
  const db = createDb(c.env.DB)
  const auth = createAuth(c.env, c.req.raw)

  c.set('db', db)
  c.set('auth', auth)

  await next()
})

// ... existing code ...

// Global Error Handler
app.onError((err, c) => {
  console.error(`[API Error] ${err}`)
  if (err instanceof HTTPException) {
    return c.json({
      success: false,
      error: err.message,
    }, err.status)
  }
  return c.json({
    success: false,
    error: 'Internal Server Error',
  }, 500)
})

// --- Routes ---

// Upload Presign Route
app.post(
  '/api/upload/presign',
  zValidator('json', z.object({
    filename: z.string(),
    contentType: z.string(),
    size: z.number().int().optional(),
  })),
  async (c) => {
    // 1. Auth Check (Must be logged in)
    const session = await c.get('auth').api.getSession({ headers: c.req.raw.headers })
    if (!session) {
      throw new HTTPException(401, { message: 'Unauthorized' })
    }

    const { filename, contentType, size } = c.req.valid('json')
    const ext = filename.split('.').pop() || 'bin'
    const key = `uploads/${session.user.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`

    // 2. Generate Presigned URL
    const uploadUrl = await generatePresignedUrl(c.env, key, contentType)
    const publicUrl = `${c.env.R2_PUBLIC_URL}/${key}`

    // 3. Record in DB (Pre-create media record)
    await c.get('db').insert(media).values({
      id: crypto.randomUUID(),
      key,
      url: publicUrl,
      mimeType: contentType,
      size: size || 0,
      variants: null, // Variants will be generated by async worker later
    })

    return c.json({
      success: true,
      uploadUrl,
      publicUrl,
      key,
    })
  },
)

// Service Protected Route (Example for Crawler)
app.post('/api/admin/sync', serviceAuth(), async (c) => {
  return c.json({ success: true, message: 'Sync received' })
})

// Better Auth Routes
app.on(['POST', 'GET'], '/api/auth/*', (c) => {
  const auth = c.get('auth')
  return auth.handler(c.req.raw)
})

// Health Check
app.get('/', (c) => {
  return c.json({
    status: 'ok',
    service: 'starye-api',
    timestamp: new Date().toISOString(),
  })
})

export default app
