/**
 * 数据库 Schema 验证脚本
 * 
 * 验证 ratings 和 aria2_configs 表是否正确创建
 * 
 * 运行方式（本地）：
 * pnpm exec wrangler d1 execute starye-db --local --command "SELECT name FROM sqlite_master WHERE type='table'"
 * 
 * 本脚本用于生成验证命令
 */

console.log('📋 数据库 Schema 验证指南\n')

console.log('## 步骤 1: 验证表是否存在\n')
console.log('运行以下命令检查所有表：')
console.log('```bash')
console.log('pnpm exec wrangler d1 execute starye-db --local --command "SELECT name FROM sqlite_master WHERE type=\'table\' ORDER BY name"')
console.log('```\n')
console.log('预期输出应包含：')
console.log('  - aria2_configs')
console.log('  - ratings')
console.log('  - player (已存在)')
console.log('  - user (已存在)')
console.log('')

console.log('## 步骤 2: 验证 ratings 表结构\n')
console.log('运行以下命令检查 ratings 表结构：')
console.log('```bash')
console.log('pnpm exec wrangler d1 execute starye-db --local --command "PRAGMA table_info(ratings)"')
console.log('```\n')
console.log('预期字段：')
console.log('  - id (text, PRIMARY KEY)')
console.log('  - player_id (text, NOT NULL)')
console.log('  - user_id (text, NOT NULL)')
console.log('  - score (integer, NOT NULL)')
console.log('  - created_at (integer, NOT NULL)')
console.log('  - updated_at (integer, NOT NULL)')
console.log('')

console.log('## 步骤 3: 验证 aria2_configs 表结构\n')
console.log('运行以下命令检查 aria2_configs 表结构：')
console.log('```bash')
console.log('pnpm exec wrangler d1 execute starye-db --local --command "PRAGMA table_info(aria2_configs)"')
console.log('```\n')
console.log('预期字段：')
console.log('  - id (text, PRIMARY KEY)')
console.log('  - user_id (text, NOT NULL)')
console.log('  - rpc_url (text, NOT NULL)')
console.log('  - secret_encrypted (text)')
console.log('  - use_proxy (integer, DEFAULT 0)')
console.log('  - created_at (integer, NOT NULL)')
console.log('  - updated_at (integer, NOT NULL)')
console.log('')

console.log('## 步骤 4: 验证 player 表的新字段\n')
console.log('运行以下命令检查 player 表结构：')
console.log('```bash')
console.log('pnpm exec wrangler d1 execute starye-db --local --command "PRAGMA table_info(player)"')
console.log('```\n')
console.log('预期新增字段：')
console.log('  - average_rating (real)')
console.log('  - rating_count (integer, DEFAULT 0)')
console.log('')

console.log('## 步骤 5: 验证索引\n')
console.log('运行以下命令检查索引：')
console.log('```bash')
console.log('pnpm exec wrangler d1 execute starye-db --local --command "SELECT name, tbl_name FROM sqlite_master WHERE type=\'index\' AND tbl_name IN (\'ratings\', \'aria2_configs\', \'player\')"')
console.log('```\n')
console.log('预期索引：')
console.log('  - idx_ratings_player_user (ratings 表, UNIQUE)')
console.log('  - idx_player_rating (player 表)')
console.log('')

console.log('## 步骤 6: 验证约束\n')
console.log('运行以下命令测试唯一约束：')
console.log('```bash')
console.log('pnpm exec wrangler d1 execute starye-db --local --command "SELECT sql FROM sqlite_master WHERE type=\'table\' AND name=\'ratings\'"')
console.log('```\n')

console.log('## 自动化验证脚本\n')
console.log('创建一个 PowerShell 脚本来自动验证：')
console.log('```powershell')
console.log('# verify-schema.ps1')
console.log('$db = "starye-db"')
console.log('')
console.log('Write-Host "验证表存在..." -ForegroundColor Yellow')
console.log('pnpm exec wrangler d1 execute $db --local --command "SELECT name FROM sqlite_master WHERE type=\'table\' AND name IN (\'ratings\', \'aria2_configs\')"')
console.log('')
console.log('Write-Host "\\n验证 ratings 表结构..." -ForegroundColor Yellow')
console.log('pnpm exec wrangler d1 execute $db --local --command "PRAGMA table_info(ratings)"')
console.log('')
console.log('Write-Host "\\n验证 aria2_configs 表结构..." -ForegroundColor Yellow')
console.log('pnpm exec wrangler d1 execute $db --local --command "PRAGMA table_info(aria2_configs)"')
console.log('')
console.log('Write-Host "\\n验证 player 表新字段..." -ForegroundColor Yellow')
console.log('pnpm exec wrangler d1 execute $db --local --command "SELECT average_rating, rating_count FROM player LIMIT 1"')
console.log('')
console.log('Write-Host "\\n验证完成!" -ForegroundColor Green')
console.log('```')
console.log('')

console.log('保存为 verify-schema.ps1 并运行：')
console.log('```bash')
console.log('.\\verify-schema.ps1')
console.log('```')
